#! /bin/sh

xwallpaper --stretch ~/wall6.jpg
/home/void/.local/bin/theme.sh
wal -R -n -e

pipewire &
redshift &
dunst &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         0
bspc config window_gap          12
bspc config focused_border_color "#ffffff"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_border_color "$color1"

setxkbmap -option grp:switch,grp:alt_shift_toggle,grp_led:scroll us,ru -variant ",phonetic"

/home/void/.local/bin/polybar.sh
